### ISSUE TITLE
How does pool min resource amount behave?

### ISSUE THREAD

**Issue by elhigu** [Vincit/tarn.js#1]
When pool is created does tarn immediately warm up and try to acquire those min number of resources to be or does min: 2 only have an effect on how many resources are left to pool when cleaning up?

**Comment by koskimas** [comment]
The pool is not filled immediately. `min` only tells how many resource to keep in the pool once they are created.

**Comment by Bessonov** [comment]
Thanks! Is there any way to acquire connections eagerly except to put some load?

**Comment by elhigu** [comment]
No and that is intentional. It makes error handling easier, since creating pool instance cannot fail due to broken resource acquire etc.
