### ISSUE TITLE
Should we throw an error if non existent parameters are passed to the pool creation 

### ISSUE THREAD

**Issue by elhigu** [Vincit/tarn.js#19]
I saw bunch of deprecated code in knex, that is trying to check and give warnings if invalid parameters are passed to tarn (checked parameter list actually didn't match with tarn...).

To me it would be more reasonable to do parameter validation by tarn instead of trying to keep up with correct attributes in knex side. Probably knex had that code, because of its old habit of changing pool on every release.

Downside of this is that throwing an error on invalid parameter would be a breaking change. I could live with that though.

**Comment by koskimas** [comment]
Seems reasonable to me.
