### ISSUE TITLE
Tarn: unsupported option opt.xxx

### ISSUE THREAD

**Issue by ImHype** [Vincit/tarn.js#33]
When I extend a new Pool from the `Tarn`, and putting the other keys on the TarnPoolOptions, to implement my requirements, likes the below.
```
{
    idleTimeoutMillis: 3000,
    acquireTimeoutMillis: 3000,
    someMyOwnKey: 'xxx'
}
```

And I transmit the options to `Tarn`，then it will give me the Error:

```
Tarn: unsupported option opt.xxx
```

This problem is from the `1.2.0` version because of these codes.
```js
const allowedKeys = {
    create: true,
    validate: true,
    destroy: true,
    log: true,
    min: true,
    max: true,
    acquireTimeoutMillis: true,
    createTimeoutMillis: true,
    destroyTimeoutMillis: true,
    idleTimeoutMillis: true,
    reapIntervalMillis: true,
    createRetryIntervalMillis: true,
    propagateCreateError: true
};
for (let key of Object.keys(opt)) {
    if (!allowedKeys[key]) {
        throw new Error(`Tarn: unsupported option opt.${key}`);
    }
}
```

I think it's a `Breaking Change` but you upgrade the `minor version`.

**Comment by elhigu** [comment]
Oh, shit. You are right, it was meant to be marked as breaking change 🤦‍♂️

Do you think I should unrelease 1.2.0 and change it to 2.0.0?

**Comment by alexandrebodin** [comment]
Hi @elhigu, It kinda is breaking a lot of stuff around here :smile
We are using `knex`which is still sending you wrong params that we passed to it which makes it hard for us to fix. 
Using v2 would be greatly appreciated !

**Comment by ImHype** [comment]
I thought it's a good Idea to unpublish the `1.2.0` version.

And these codes need appear in the version `2.0.0`.

If you don't want to publish a major-upgrade version, you could add a option to switch the strict mode (Checking the unused options),

**Comment by kibertoad** [comment]
@elhigu In order to provide a migration path, maybe we should have some field along the lines of `userParams` or `customParams`, where users can hold their config values if they need to? Seems like a valid case.

**Comment by elhigu** [comment]
I believe its an invalid use case, because tarn is not really made to be extendable... I mean when extending I don't see that you can do much else, except for adding some default parameters and maybe hooks in, which should be done with composition in a more clean way where pool is inside your own object.

If anyone likes, we can keep on discussing if extending is really necessary (even in that case one can filter extra parameters out before passing them to super constructor).

I'll unpublish + re-release it as 2.0.0. and just see how many people are complaining about missing 1.2.0 version that their CI already got. Thanks for notice and I'm sorry about the hassle.

**Comment by alexandrebodin** [comment]
@elhigu Throwing on invalid params seems to be the right move for sure ;) as long as it's a major release 😄 

Thank you for your reactivity !

**Comment by elhigu** [comment]
Now 1.2.0 is unpublished and tarn 2.0.0 is out. I also added mention to changelogs about unpublished version.

**Comment by ImHype** [comment]
Thanks all guys.

I extend the Pool from tarn because of these reasons:
1. I could replace the core Pool SDK easyly if the Pool SDK is not high-avaliable. Of course, it was migrated from the `genric-pool`;
2. I could split my logic to some layers. For example, if I need make a Pool for Thrift Connection, I could split the logic to `net-pool` and `thrift-pool` and the `thrift-pool` could extend from the `net-pool` to reuse some common operations.

I thought the Tarn is a excellent Resource Pool SDK by this communication. I would love to join the development if possible. 

:)

Thanks again.

**Comment by elhigu** [comment]
Thanks @ImHype everyone is welcome to join development, so feel free to discuss about features / bugs in issues and if they seem to give enough value to the lib PRs are also welcome 👍  

But honestly there is not much to do for this package. Main point to consider on every feature request is `Tarn will always remain simple.` and that tarn was built for knex.

So probably there won't be much new features added unless they are crucial for knex or if they are not making tarn more robust :)

(even that `.on()` hooks feature was on the edge of being too much, but it actually already proved to be useful, when I wrote tests and found out some bugs from current code just by looking those events)

**Comment by elhigu** [comment]
Also if someone likes to create more featured pool, using tarn for its core functionality doesn't sound like a bad idea at all. I know some people would love to have swissarmyknife type of pool :)
