### ISSUE TITLE
npm ERR! notarget No matching version found for tarn@1.2.0

### ISSUE THREAD

**Issue by reutopiaer** [Vincit/tarn.js#35]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for tarn@1.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'content-type-builder'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:

**Comment by elhigu** [comment]
That version was published by accident and then unpublished. More info in https://github.com/Vincit/tarn.js/issues/33 use 2.0.0 instead.

**Comment by elhigu** [comment]
Probably I should have also publish 1.1.5 as 1.2.1 so that latest version would have been updated automatically for those who had fetched 1.2.0 when it was available.
