### ISSUE TITLE
feature request: asynchronous validate function

### ISSUE THREAD

**Issue by joseph349** [Vincit/tarn.js#44]
I am using knex 0.15.2 along with tarn 1.1.4.
Have been getting the "This socket has been ended by the other party." recently when trying to use a connection that has been closed or redirected by the server.
We have found that we may be able to avoid this error by pinging the connection in the validation function.
Problem we're having is that the validation function is synchronous and there is no way for it to wait for the ping promise to resolve. 
Can we have the validate function resolve async functions?

**Comment by elhigu** [comment]
I thought it already was async, but looks like it is actually not. I'll fix this for the next release.

**Comment by joseph349** [comment]
Is the work is already done? Is there a branch that we can use?

**Comment by elhigu** [comment]
No. I just started to look into it.

**Comment by elhigu** [comment]
This is actually pretty fundamental change and will need major release (strictly speaking it is not breaking change, but internal acquire behaviour changes significantly so better to do full release for this).

**Comment by elhigu** [comment]
PR #45

**Comment by joseph349** [comment]
Has this been published to npm?

**Comment by elhigu** [comment]
not yet, I'll make a release when I have time

**Comment by eugene1g** [comment]
Looks like this feature has been shipped in v3.0 @ https://github.com/Vincit/tarn.js/commit/b577cfc3b1e2f193c5a6a18645f5ac97dcc75600

**Comment by elhigu** [comment]
true
