### ISSUE TITLE
Need a hook for connection acquire to call a query for Postgres Row Level Security

### ISSUE THREAD

**Issue by cxonexus-github-admin** [Vincit/tarn.js#54]
We are implementing a multitenant db and would like the enforce row level security using a parameter enforced when a connection is acquired. We use Knex, so the call to tarn is baked in. Any thoughts on perhaps an event handler that could be passed the current connection?

**Comment by elhigu** [comment]
Acquire/destroy, etc. callbacks are implemented in knex side, those should be able to be used and knex should allow actually override those functions to have custom implementation. I don't think there is anything that tarn should support here. Tarn actually doesn't know anything about the resources it creates / leases.

Also it is not clear what is tried to be achieved here exactly. Also one viable solution could be to create multiple knex instances for different tenants.
