### ISSUE TITLE
Error: Cannot clear timer: timer created with setInterval() but cleared with clearTimeout()

### ISSUE THREAD

**Issue by JulesAU** [Vincit/tarn.js#6]
Using Tarn in Knex.  Upon destroying connection (hence pool) I get:

```
Error: Cannot clear timer: timer created with setInterval() but cleared with clearTimeout()
```

Which makes sense, given that the reaper is set with [setInterval](https://github.com/Vincit/tarn.js/blob/04ba822a7a4c753a81b993ba1158f541145e3af0/lib/Pool.js#L335) and we attempt to shut it down with [clearTimeout](https://github.com/Vincit/tarn.js/blob/04ba822a7a4c753a81b993ba1158f541145e3af0/lib/Pool.js#L340)

Changing it to `clearInterval` fixes it, and results in the pool correctly being torn down.

**Comment by koskimas** [comment]
Weird. While this should be fixed, I've never seen that error before and I've been mixing `setInterval` with `clearTimeout` for years. I just now ran the commands in node with no error.

Which node version are you using?

**Comment by JulesAU** [comment]
This was node v8.6.0. Thanks!

**Comment by koskimas** [comment]
@JulesAU I ran the tests with node 8.6.0 with the old code and it produced no errors. You must have overridden the `setInterval` and `clearTimeout` handlers somehow? I'm just trying to figure out how you got that error. The only thing I could find on the internet was this

https://github.com/sinonjs/sinon/issues/872

**Comment by JulesAU** [comment]
Ahhh yep that would be it.. my bad :-/  We use sinon with Mocha. That must have been where I saw it.

Sorry!
