### ISSUE TITLE
acquire() fails immediately with TimeoutError if pool in a weird state

### ISSUE THREAD

**Issue by mdoliner-st** [Vincit/tarn.js#61]
Hi! I think I'm seeing a problem where the promise returned by `acquire()` is immediately rejected with TimeoutError (much sooner than acquireTimeoutMillis). I'm still narrowing down the exact repro steps, but it's something like:

1. Create a new pool.
2. Acquire all the resources allowed by `max` and hold them.
3. Call `acquire()` more times and wait for these to time out.
4. Release the resources.
5. Call `acquire()` again. This should succeed but it doesn't. The returned promise is immediately rejected with TimeoutError.

I've tried adding a bunch of debugging code and right before step 5 I believe `pendingCreates`, `pendingAcquires`, and `pendingDestroys` are all empty lists. `free` contains resources. The number of resources doesn't seem to matter. It seems like this happens if it's 1 or `max`. So it _seems_ like there must be a leftover TimeoutError on the `Resource` in the `free` list. But I'm having a hard time wrapping my head around how all this works so I might be wrong about all of this.

I'm testing this via Objection and knex, so I also can't eliminate those as the source of the problem I'm seeing.

I'll try to write some repro code for this soon.

**Comment by elhigu** [comment]
Thanks for report. I'm rewriting parts which are also related to that area of code, so would be good to have test case to see if it gets fixed on the way.

**Comment by mdoliner-st** [comment]
Good news! I think I was wrong and this isn't actually a bug in Tarn. It seems like it's actually in Objection. At least I wasn't able to reproduce it in Tarn or Knex. I was only able to reproduce with Objection. https://github.com/Vincit/objection.js/issues/1997

**Comment by kibertoad** [comment]
@mdoliner-st Which DB are you using, btw?

**Comment by mdoliner-st** [comment]
I'm using PostgreSQL but it also happens for sqlite3, which is what I used in the repro case I linked to in the Objection GitHub issue.
