### ISSUE TITLE
Event Emitter methods missing (.once) and (.off)

### ISSUE THREAD

**Issue by alexp1917** [Vincit/tarn.js#62]
the pool exposes `.on()` which makes the user think its an Event Emitter, but the pool adds additional complexity by having the event emitter as a field. If this approach were to stay, the pool should also expose `.once`, `.off`, etc.

It is even marked `protected` in the type annotation, which doesn't affect me but may affect developers who use tooling for that.

If waiting for the pool to release some resources, it is possible to do the following

```js
var { once } = require('events');
(async () => {
  await once(pool.emitter, 'release');
  console.log('i can send more requests now');
})();
```
it would be more intuitive to do `await once(pool, 'release')` but internally this calls "once" which is not copied onto the pool class - it seems like this is something which is definitely useful for a pool so if there is another way to do it, I would be very interested to know.

**Comment by alexp1917** [comment]
@elhigu yeah i've been struggling to figure out how to listen for the event when the pool is healthy again anyways, any ideas on how i should go about that?

**Comment by elhigu** [comment]
Also those hooks were introduced to be used as a diagnostic events if one likes to monitor pool's internal events for debugging and statistics. 

There is no such event and pool really doesn't know anything about the resources it is creating and returning. For example with knex you just need to do for example `.select(1)` queries until it does not throw an error anymore.

**Comment by alexp1917** [comment]
@elhigu how do you feel about merging a PR which adds the ability to detect when a pool is healthy again?

> Tarn is focused on robustness and ability to recover from errors.

my application was going to be to consumer a kafka topic --- sometimes the stream sends too much at a time, and for that reason i have to pause it, wait for the pool to become healthy, and then unpause. this is applicable for any stream of events really, i think. really just looking to gauge how welcome this change is in this project (maybe i should go make my own resource pool entirely? this one even says what i want to say for my own justification.)

**Comment by elhigu** [comment]
What do you mean by "pool is healthy again"? Pool is healthy all the time.

Do you meant to be able to have an event launching when pool is full / there are free resources in the pool?

**Comment by alexp1917** [comment]
I mean when the underlying resource is able to be used again, instead of just retrying in application code, move this responsibility to the library, perhaps the first free resource, or when there are no longer any resources in the acquire queue, or when n or x% of the resources are free.

**Comment by elhigu** [comment]
> I mean when the underlying resource is able to be used again

How would tarn know such thing? Tarn does not poll any of the resources. It just responds if someone requests one (returns a previously created free one or if no free resources left and there is room in pool for more it calls create callback to create a new one and if create fails it returns an error).

> instead of just retrying in application code, move this responsibility to the library

Actually there is an option (which should never be used with knex) to instead of returning the error tarn will retry the create if it does fail until some timeout is reached.

> the first free resource, or when there are no longer any resources in the acquire queue, or when n or x% of the resources are free.

One thing that tarn could maybe provide is to create an event when numFree/numUsed etc. values are changed. That would not be too opinionated.

> On second thought, ill just combine with a circuit breaker library.

Yes, sounds like a good idea. Tarn should not try to implement that kind of features.

**Comment by alexp1917** [comment]
> How would tarn know such thing?

I mean - I am calling a database under heavy use "unhealthy", if queries start taking too long, then requests will pile up, then they will exhaust the pool. i mean having tarn throw the TimeoutError and circuit breaker catch this, keep a list of errors in the sliding scale, and emit events based on that seems super inefficient.

> One thing that tarn could maybe provide is to create an event when numFree/numUsed etc. values are changed. That would not be too opinionated.

This is what i had in mind; I will think about this and see if i can make a thoughtful proposal in a new issue.
