### ISSUE TITLE
`@types/node` needs to be declared as a dependency for this package to work with typescript and yarn v2

### ISSUE THREAD

**Issue by mprast** [Vincit/tarn.js#64]
yarn v2 is a little stricter about dependencies than yarn v1 or npm. If a package abc imports another package xyz without having an explicit dependency on it, yarn v2 will not resolve the import - which is to say, this package breaks when used with typescript and yarn v2 (tsc complains about not being able to find a type definition file for @types/node). Please consider adding a dependency on @types/node for the yarn v2 users out there - thank you!

**Comment by elhigu** [comment]
It can be added. It is enough to have it as development dependency right?

**Comment by mprast** [comment]
No, I believe it needs to be listed in the normal `dependencies` field. From the [yarn docs](https://yarnpkg.com/configuration/manifest#devDependencies) entry for `devDependencies`: 

> Similar to the dependencies field, except that these dependencies are only installed on local installs _and will never be installed by the consumers of your package_

My guess is that if package A isn't explicitly installed as a dependency of package B by yarn v2 at runtime, yarn v2 will refuse to resolve a request for package A from package B, even if package A was installed as a dependency of some other package.

Empirically, typescript compilation succeeds when I add `@types/node` as a normal dependency of `tarn` via the `yarn.lock` file, and fails when I try to use `tarn` as-is (with `@types/node` only declared as a dev dependency). 

Thanks for taking a look!
