### ISSUE TITLE
It seems tarn breaks create-react-app compilation

### ISSUE THREAD

**Issue by YagoLopez** [Vincit/tarn.js#7]
Hello. As far as I know a project based on create-react-app needs its dependencies compiled to ES5 but it seems that `tarn` package only provides ES6 code. Could your provide any help?

Here is the error I get:
```shell
Failed to minify the code from this file:

 	./node_modules/tarn/lib/utils.js:6

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metaphasejs-react-demo@0.1.0 build: `react-scripts-ts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metaphasejs-react-demo@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yagol\AppData\Roaming\npm-cache\_logs\2018-05-27T18_35_40_031Z-debug.log
```

**Comment by koskimas** [comment]
That error doesn't really say anything. I'm sorry, but I don't have time to solve this for you. You need to google that your self.

Tarn is written in node 4.0.0 compatible ES6 code. We won't support older nodes or rewrite the project in ES5.

**Comment by koskimas** [comment]
Oh, and I forgot to mention that only node is officially supported, not browsers.

**Comment by YagoLopez** [comment]
What the error says is create-react-app can't compile code in ES6. It does not mean `tarn` has got errors.

It is explained following the link in the error message: http://bit.ly/2tRViJ9

It is considered a good practice to provide code following ES5 standard in npm packages as the CRA docs say also.

**Comment by koskimas** [comment]
> It is considered a good practice to provide code following ES5 standard in npm packages as the CRA docs say also.

Yup, for browser. But as I said, browsers are not officially supported by this project.
