### ISSUE TITLE
Curious behavior with idle timeouts (Postgres)

### ISSUE THREAD

**Issue by olivierlacan** [Vincit/tarn.js#73]
We're using Knex 0.95.15 with tarn 3.0.2 and noticed some of our CI runs are hanging for many seconds past mocha's exit. After adding [wtfnode](https://www.npmjs.com/package/wtfnode) to investigate we see the following open handles and timers running past the end of our test suite: 

```
- Timers:
1909  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1910  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1911  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1912  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1913  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1914  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1915  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1916  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1917  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1918  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1919  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1920  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1921  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1922  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1923  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1924  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1925  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1926  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1927  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
1928  - (10000 ~ 10 s) (anonymous) @ /node_modules/.pnpm/pg-pool@3.4.1_pg@8.6.0/node_modules/pg-pool/index.js:324
```

There's very likely something I missed here, but this doesn't feel right since [the Tarn idleTimeoutMillis defaults to `30000`ms](https://github.com/Vincit/tarn.js/blob/master/src/Pool.ts#L138). Even when I set it (through Knex) lower, this issue still occurs with 10 second timeouts and clearly seems to originate from `pg-pool` and not Tarn. 

There's a [section in Knex' `PoolConfig` types that explicitly references Tarn configs in a way that appears separate](https://github.com/knex/knex/blob/71fd863664e681cd6d451364b2c4368ce213b529/types/index.d.ts#L2626-L2644) from the rest of the PoolConfig interface, which makes me curious.

My expectation was that changing `idleTimeoutMillis` in our Test environment would impact these timeouts. Interestingly, node-postgres [recently added](https://github.com/brianc/node-postgres/pull/2568) a (false defaulted) [config to `allowExitOnIdle`](https://github.com/brianc/node-postgres/blob/2c3adf25f94358defb84f14ca50f6873a3340618/packages/pg-pool/index.js#L329-L332) which feels like it could be useful here but I can't set it through Knex/Tarn since it's not allowed by the `PoolConfig` interface. 

Despite looking into this for quite a while now I can't quite seem to find where Knex/Tarn interact with node-postgres and where these configs would be clashing. I'd be grateful if anyone has pointers, and hopefully someone encountering similar issues can benefit from my research. 🙃

**Comment by sharadpattanshetti** [comment]
We tried using the below config for our application but it still shown max 10 connections when checked through hooks: 

`database:
    knexConfig:
      pool: 
        min: 0
        max: 20
        acquireTimeoutMillis: 60000
        idleTimeoutMillis: 600000`

----------------------------- 
` const db = await database.getClient();
  const pool = db.client.pool;  
  pool.on('release', (resource: { __knexUid: any; }) => {
    logger.info(`connection on release -  used: ${pool.numUsed()}, free: ${pool.numFree()}, waiting:${pool.numPendingAcquires()}`)
    logger.info(`connection on release - resource id : ${resource.__knexUid}`)
  });`

Any suggestions?

**Comment by mautematico** [comment]
@olivierlacan see: https://github.com/Vincit/tarn.js/pull/74/files

**Comment by elhigu** [comment]
I think since tarn does not depend from knex nor posgresql, this should be knex issue. Knex creates internally tarn pool and adds necessary handlers to create/destroy resources etc. 

Usually if CI hangs after mocha exists, there are some timers etc. still running. Maybe you did not call knex.destroy() when CI is tearing down?

Adding that `allowExitOnIdle` parameter support needs to be also implemented in knex.

Closing, since this does not seem to be tarn issue.
