### ISSUE TITLE
Increase timeout request

### ISSUE THREAD

**Issue by LeonardoJavierTorrealba** [Vincit/tarn.js#77]
I have placed in my configuration in all possible ways modifiers of the timeout but it never changes from 1500ms.
**"RequestError: Timeout: Request failed to complete in 15000ms"**. I always get at the timeout error, which exceeds 1500ms.  Thanks for the help.

     
```
       dbSettings: {
                user: 'abcd',
                password: 'abcd',
                server: 'abcd',
                database: 'abcd',
                setTimeout: 900000,
                connectionTimeout: 900000,
                requesTimeout: 900000,
                pool:{
                    idleTimeoutMillis: 90000
                    },
                options:{
                    encrypt: false, 
                    trustServerCertificate: true,
                    }
               }
```

**Comment by elhigu** [comment]
That config seems to be invalid. Check knex documentation and tarn.js docs for tarn config parts https://github.com/Vincit/tarn.js#usage
