### ISSUE TITLE
Should Pool create minimum number of free connection in consturctor?

### ISSUE THREAD

**Issue by jpham005** [Vincit/tarn.js#82]
Currently, it seems that Pool doesn't make free connections in consturctor, so when first `acquire` call, Pool always have to create new connection.

I think it should create a minimum number of free connections and keep it.
Or just provide `init` method to create connections.

Is this behavior is intended or not?

**Comment by elhigu** [comment]
That is a good question and it is intended behavior. Minimum affects only for freeing that if pool has already allocated over min amount of resources, it will not free all of them. IIRC the reasoning was to make error handling easier when just creating the pool will not have to register additional error handlers for cases where acquiring initial resources fail asynchronously.

This way client will actually get the error if (initial) acquires fail. 

Pool could have a separate `async function warmup()` to mitigate that problem, but most of the people does not care about warming up the pool and that is also trivial to implement in the application side.

**Comment by jpham005** [comment]
Got it. Thanks for nice reply!
